name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
            
    - name: publish-windows
      working-directory: ${{env.GITHUB_WORKSPACE}}
      ###run: dotnet publish -c Release -f ${{ env.NETVERSION }} -p:RuntimeIdentifierOverride=win10-x64 -p:SelfContained=true -p:PublishSingleFile=true -p:WindowsAppSDKSelfContained=true
      run: dotnet publish -c Release -r win-x64 -p:EnableWindowsTargeting=true --self-contained true -p:PublishSingleFile=true -o ./publish

    # - name: publish-linux
      # working-directory: ${{env.GITHUB_WORKSPACE}}
      # run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./linux-x64/ACNHPockets-app       
      
      
      ###dotnet publish -c Release -r linux-x64 --self-contained true -o ./publish_ubuntu
      
    - name: Show Github infos
      run:  echo 'Workspace path ${{ github.workspace }} - runner.temp ${{ runner.temp }}'     
      
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ github.token }} 
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}

    # - name: Zipping up Release folder
      # run: zip -r release.zip ${{ github.workspace }}/publish
            
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false    
        tag_name: ${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}
        files: "${{ github.workspace }}/publish/Led Digital Clock.exe"
      env:
        GITHUB_TOKEN: ${{ github.token }} 
        

        